details:
  name: Front End Web Development
  repository_name: unit-front-end-web-development

sequence:
  JavaScript Utilities (Built-in Methods -> Error Handling):
    - name: Unit 2 Launch
      elements:
        - kind: deck
        - kind: recording
    - name: Built-in Methods
      pursuit_path: built-in-methods
      kind: lesson
      activity: repository
    - name: Modern JavaScript Features
      pursuit_path: modern-javascript-features
      kind: lesson
      activity: repository
    - name: Higher Order Functions
      pursuit_path: higher-order-functions
      kind: lesson
      activity: repository
    - name: Higher Order Native Array Methods
      pursuit_path: higher-order-native-array-methods
      kind: lesson
      activity: repository
    - name: Error Handling
      pursuit_path: error-handling
      kind: lesson
      activity: repository
    - name: Mid-Unit front-end-web-development assessment
      pursuit_path: mid-fewd
      kind: assessment
      activity: repository
      points_possible: 7
  HTML & CSS:
    - name: Introduction to HTML
      pursuit_path: intro-to-html
      kind: lesson
      activity: repository
    - name: Deploy with GitHub Pages
      elements:
        - kind: guide
          pursuit_path: deployment
          pursuit_subpath: github-pages
        - kind: recording
    - name: Understanding Front-end Tests
      pursuit_path: understanding-front-end-tests
      kind: lesson
      activity: ~ # none
    - name: Introduction to Forms
      pursuit_path: intro-to-forms
      kind: lesson
      activity: repository
    - name: Introduction to CSS
      pursuit_path: intro-to-css
      kind: lesson
      activity: repository
    - name: CSS selectors
      pursuit_path: css-selectors
      kind: lesson
      activity: repository
    - name: CSS Box Model
      pursuit_path: css-box-model
      kind: lesson
      activity: repository
    - name: CSS Grid
      pursuit_path: css-grid
      kind: lesson
      activity: repository
    - name: CSS Media Queries
      pursuit_path: css-media-queries
      kind: lesson
      activity: repository
  DOM Manipulation:
    - name: Request-Response Cycle
      pursuit_path: request-response-cycle
      kind: lesson
      activity: ~ #none
    - name: Document Object Model
      pursuit_path: document-object-model
      kind: lesson
      activity: ~ # none
    - name: Reading and Deleting DOM Elements
      pursuit_path: reading-deleting-dom-elements
      kind: lesson
      activity: repository
    - name: Creating and Updating DOM elements
      pursuit_path: creating-updating-dom-elements
      kind: lesson
      activity: repository
    - name: Events
      pursuit_path: events
      kind: lesson
      activity: repository
    - name: Forms with Events
      pursuit_path: forms-with-events
      kind: lesson
      activity: repository
  Asynchronous Actions (API Calls):
    - name: API Calls with Postman
      pursuit_path: api-calls-with-postman
      kind: lesson
      activity: ~ # none
    - name: Deployment
      elements:
        - kind: guide
          pursuit_path: deployment
          pursuit_subpath: github-pages
        - kind: recording
    - name: Promises
      pursuit_path: promises
      kind: lesson
      activity: repository
    - name: API Calls with Fetch
      pursuit_path: api-calls-with-fetch
      kind: lesson
      activity: repository
    - name: Weather App Project
      pursuit_path: weather-app
      kind: project
      activity: repository
      points_possible: 9
    - name: Front-end Portfolio Project
      pursuit_path: front-end-portfolio
      kind: project
      activity: repository
      points_possible: 29
    - name: End of Unit
      pursuit_path: final-fewd
      kind: assessment
      activity: repository
      points_possible: 8
    - name: End of Unit Reflection
      elements:
        - kind: deck
        - kind: recording
